# Generated by Django 4.2.19 on 2025-03-10 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_remove_task_description_remove_task_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resuelta',
            field=models.BooleanField(default=False),
        ),
    ]
