# Generated by Django 4.2.19 on 2025-03-10 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_resuelta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='resuelta',
            new_name='resuelto',
        ),
    ]
