# Generated by Django 4.2.19 on 2025-03-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_fecha_asignacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='resuelto',
        ),
    ]
