# Generated by Django 4.2.19 on 2025-03-10 18:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_resuelta_task_resuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='fecha_asignacion',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
