# Generated by Django 4.2.19 on 2025-03-11 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_task_resuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='resuelto',
            field=models.BooleanField(default=False),
        ),
    ]
