# Generated by Django 4.2.19 on 2025-03-13 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_resuelto'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('sin_prioridad', 'Sin prioridad'), ('muy_baja', 'Muy baja'), ('baja', 'Baja'), ('alta', 'Alta'), ('muy_alta', 'Muy alta'), ('urgente', 'Urgente')], default='sin_prioridad', max_length=20),
        ),
    ]
